node: 999
server:
    port: 9099
    context-path: /links86trade
logging:
    level:
        com.links86.trade: DEBUG
spring:
    mvc.view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    datasource:
        url: jdbc:mysql://127.0.0.1/links86?useUnicode=true&characterEncoding=UTF-8
        username: root
        password:
        testWhileIdle: true
        validationQuery: SELECT 1
        sql-script-encoding: utf-8
        ## update 替换为create-drop 默认创建
    jpa:
        show-sql: true
        hibernate:
            generate-ddl: true
            ddl-auto: update
        properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
#            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#####   以下是 aplipay 支付接口的配置
#####  两个回调都必须是绑定公网域名才会有返回
####    正式生产之后此两个key都需要修改掉！
com:
   alipay:
        partner: 2088421743486096
        seller_id: 2088421743486096
        key: ow8q96gwfkf7yh0v7l4v3cfv4d9s1lcm
        private_key: MIICeQIBADANBgkqhkiG9w0BAQEFAASCAmMwggJfAgEAAoGBALEV10TbY5SMJglB8sZeMzatT2sBMiKLYZXyJbEbJA0ulVFcdjGE5E7jb3tZrFO0o5L5VmsTGwJNzBeS+MM2QynnaixrRtHpgyZrkpgVssZsMiikIYZWwwkZhHe8qsayxYdkwxp7I3kUAOvTmlHYaN0Um3riY/unKNLxwqKNsj6NAgMBAAECgYEAp9dvpY/bHlyHYJblKCb4m4ZAk8caYauB3sEYAHkc/nF8jRT54Y13Z14ht+QSdXPs5cz1n58IJnLeUim3Ji80D9pXrwrBxft8EagMSsaw1MckvVt0QCwAJIZ/wTLmTy2xQovpAH1mm5eMSX4Q/nDojRUiQ2i2Za6q5+rGPWk1hXECQQDop057cmQ01x1oqXhJ58ksdVSQ/pmHiTsVyp5ITyYzRK7KSNfq9Uf17ypYd40ShdIevj6daUaBBkTJH8SULq8bAkEAwtsHVnr1uHz3Crut2p1kpREADoOQNelOD7Wp1YYzKupeEEAU8EKpmXqMZ7juV07ITa8bfAQpCUAWFufXPAUbdwJBAM3sIAwlwMoASNh1f7GyhZ5jL3my0ANmFLUCBT0tSTuBpFAJT4t4lLv6d3mcP3JQnh11+AftwWi8Oq/l/WHHPFcCQQC+A+NK9QtLxikOgWiPSG8N/N8GSEvIFuQ1s5yTiZO6JORnimYgyZEkBvqGZzOdVklEYB84N8Jgr+samSkt8XkPAkEAjHBR2cmSwSuYXJL45WZB7GwiwtaUXEHxSmg5fCl6rDbreM9wYOwFKXZsnZpPsEX9IyhJ8jvMoxs2zqHpFGbtuw==
        alipay_public_key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCnxj/9qwVfgoUh/y2W89L6BkRAFljhNhgPdyPuBV64bfQNN1PjbCzkIM6qRdKBoLPXmKKMiFYnkd6rAoprih3/PrQEB/VsW8OoM8fxn67UDYuyBTqA23MML9q1+ilIZwBC2AQ2UBVOrFXfFl75p6/B5KsiNG9zpgmLCUYuLkxpLQIDAQAB
        notify_url: http://t3.86links.com/links86trade/trade/notify_url
        return_url: http://t3.86links.com/links86trade/trade/return_url
        sign_type: MD5
        log_path: ../logs
        input_charset: utf-8
        payment_type: 1
        service: create_direct_pay_by_user
        fail_return_url: http://t3.86links.com/#/homepage/payVIPFail
        success_return_url: http://t3.86links.com/#/homepage/payVIPsuccess

####   paypal 正式环境下配置
####   mode 需修改为live
####   userName password signature 都来源于商家账户  查询连接http://www.putler.com/support/faq/how-to-get-paypal-api-username-password-and-signature-information/
####   login_url   https://www.paypal.com/cgi-bin/webscr  移出测试环境的sandbox
   paypal:
        mode: sandbox
        userName: jb-us-seller_api1.paypal.com
        password: WX4WTU3S8MY44S7F
        signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu
        return_url: http://t3.86links.com/links86trade/trade/paypal_return_url
        login_url: https://www.sandbox.paypal.com/cgi-bin/webscr
        success_return_url: http://t3.86links.com/#/homepage/payVIPsuccess
        fail_return_url: http://t3.86links.com/#/homepage/payVIPFail
crossDomainFilter:
    origin: "*"


